baseURL = 'https://example.org/'
languageCode = 'en-us'
theme = 'Stack'

title = "Apihte's Site"

# defaultContentLanguage = "zh-cn"
# languageCode = 'zh-cn'
# languageName = '简体中文'

# 是否包括中日韩文字
hasCJKLanguage = true
# 默认每页列表显示的文章数目
paginate = 12
# 谷歌分析代号 [UA-XXXXXXXX-X]
googleAnalytics = ""
# 版权描述，仅仅用于 SEO
copyright = ""

# 是否使用 robots.txt
enableRobotsTXT = true
# 是否使用 git 信息
#enableGitInfo = true
# 是否使用 emoji 代码
enableEmoji = true